### ISSUE TITLE
TODO: Rewrite JS

### ISSUE THREAD

**Issue by TBarregren** [Kntnt/kntnt-parallax-images#1]
- [x] The code should not be jQuery plugin.
- [ ] Setup proper JavaScript project for JS code.
- [ ] U Babel to transpile JS.
